### ISSUE TITLE
 What is the magic string at KeymaestroHybridEncrypter?

### ISSUE THREAD

**Issue by Kolyall** [yongjhih/pepk#1]
```
def encryptedPrivateKey = new KeymaestroHybridEncrypter("eb10fe8f7c7c9df715022017b00c6471f8ba8170b13049a11e6c09ffe3056a104a3bbe4ac5a955f4ba4fe93fc8cef27558a3eb9d2a529a2092761fb833b656cd48b9de6a".decodeHex())
```

What is the magic string `"eb10fe8f7c7c9df715022017b00c6471f8ba8170b13049a11e6c09ffe3056a104a3bbe4ac5a955f4ba4fe93fc8cef27558a3eb9d2a529a2092761fb833b656cd48b9de6a"`?

**Comment by knispeja** [comment]
@Kolyall It's the public Google encryption key for app signing -- Google actually provides this information when trying to change your app signing key via the Play Console, but it's kind of hidden

![image](https://user-images.githubusercontent.com/9343160/220001453-17517c36-ba0e-450a-a4b0-55276e223ce8.png)

**Comment by leeyisoft** [comment]
<img width="339" alt="image" src="https://github.com/yongjhih/pepk/assets/6138668/eae08081-dbff-4990-ab4c-871976f9c8f6">

java -jar pepk.0.0.1.jar --keystore sign-keystore.jks --alias sign --output=sign.zip --encryptionkey=eb10fe8f7c7c9df715022017b00c6471f8ba8170b13049a11e6c09ffe3056a104a3bbe4ac5a955f4ba4fe93fc8cef27558a3eb9d2a529a2092761fb833b656cd48b9de6a --include-cert
